[package]
name = "fuzzy-search"
version = "0.1.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2021"
description = "collections for fuzzy search"
repository = "https://github.com/ynqa/fuzzy-search"
license = "MIT"
readme = "README.md"

[dependencies]
rayon = "1.7.0"
anyhow = "1.0.75"
